export const menuData= () => {
  const data = [
    {
      id: 1,
      name: "Tandoori",
      items: [
        {
          name: "Garlic Naan",
        },
        {
          name: "Cheese Butter Naan",
        },
        {
          name: "Stuffed Naan",
        },
        {
          name: "Cheese Naan",
        },
        {
          name: "Butter Naan",
        },
        {
          name: "Plain Kulcha",
        },
        {
          name: "Butter Kulcha",
        },
        {
          name: "Missi Roti",
        },
        {
          name: "Pain Roti",
        },
        {
          name: "Stuffed Naan",
        },
        {
          name: "Butter Roti",
        },
        {
          name: "Plain Roti",
        },
        {
          name: "Kashmiri Naan",
        },
        {
          name: "Alu Parotha",
        },
        {
          name: "Khasta Roti",
        },
        {
          name: "Mixi Roti",
        },
        {
          name: "Jira Roti",
        },
        {
          name: "Fudina Roti",
        },
        {
          name: "Laccha Paratha",
        },
      ],
    },
    {
      id: 2,
      name: "Roti",
      items: [
        { name: "Rotala Churma" },
        { name: "Butter Rotalo (Bajri)" },
        { name: "Plain Rotalo (Bajri)" },
        { name: "Butter Tava Parotha" },
        { name: "Fry Parotha" },
        { name: "Plain Tava Roti" },
        { name: "Butter Tava Roti" },
      ],
    },
    {
      id: 3,
      name: "Chinese Starter",
      items: [
        { name: "Baby Con Chilli Dry" },
        { name: "Paneer Chilli Dry" },
        { name: "Veg. Manchurian Dry" },
        { name: "Chinese Bhel" },
        { name: "Panner chilli Gravy" },
        { name: "Veg. Manchurian Gravy" },
        { name: "Veg. Manchurian fry Rice" },
        { name: "Veg. fry Rice" },
        { name: "Paneer 65 Dry" },
        { name: "Panner Manchurian Dry" },
        { name: "Masrum Chilli Dry" },
        { name: "Spring Roll" },
        { name: "Potato Chilli Dry" },
        { name: "Dragon Potato" },
        { name: "Veg. Crispy Dry" },
      ],
    },
    {
      id: 4,
      name: "South Indian",
      items: [
        { name: "Masala Dosa" },
        { name: "Mesur Masala Dosa" },
        { name: "Mesur Sada Dosa" },
        { name: "Cheese Masala Dosa" },
        { name: "Sweet Corn Dosa" },
        { name: "Mini Roll Dosa" },
        { name: "Mini Roll Masala Dosa" },
        { name: "Gotla Dosa" },
        { name: "Mini Tirvel Masala Dosa" },
        { name: "Mini Tirvel Sada Dosa" },
        { name: "Jumbo Masala Dosa" },
        { name: "Jumbo sada Dosa" },
        { name: "Pizza Masala Dosa" },
        { name: "Cheese Roll Masala Dosa" },
        { name: "Cheese Roll Sada Dosa" },
        { name: "Cheese Mesuri Masala Dosa" },
        { name: "Cheese Mesuri Sada Dosa" },
        { name: "Kesari Masala Dosa" },
        { name: "Tomato Uttapam" },
        { name: "Onian Uttapam" },
        { name: "Masala Uttapam" },
        { name: "Mix Uttapam" },
        { name: "Sweet Kashmiri Uttapam" },
      ],
    },
    {
      id: 5,
      name: "Panjabi Variety",
      items: [
        { name: "Paneer Butter Masala" },
        { name: "Paneer Tikka Masala" },
        { name: "Paneer Bhurji" },
        { name: "Paneer Toofani" },
        { name: "Paneer Angara" },
        { name: "Paneer Kadai" },
        { name: "Paneer Handi" },
        { name: "Paneer Do Pyaza" },
        { name: "Paneer Tawa Masala" },
        { name: "Paneer Hariyali" },
        { name: "Paneer Chatpata" },
        { name: "Paneer Jaypuri" },
        { name: "Paneer Makhani" },
        { name: "Paneer Pasanda" },
        { name: "Paneer Lajwab" },
        { name: "Paneer Patiyala" },
        { name: "Paneer Khada Masala" },
        { name: "Paneer Korma" },
        { name: "Paneer Lasaniya" },
        { name: "Paneer Kolapuri" },
        { name: "Paneer Mashroom masala" },
        { name: "Paneer Darbari" },
        { name: "Paneer Mumtaj" },
        { name: "Paneer Lavabdar" },
        { name: "Paneer Kaju cheese Masala" },
        { name: "Shahi Paneer" },
        { name: "Palak Paneer" },
        { name: "Mutter Paneer" },
        { name: "Cheese Paneer" },
        { name: "Cheese Rajwadi" },
        { name: "Cheese Anguri" },
        { name: "Cheese Paneer Masala" },
        { name: "Cheese Butter Masala" },
        { name: "Paneer Silsila" },
        { name: "Paneer Balti" },
        { name: "Paneer Tiranga" },
        { name: "Jeera Alu" },
        { name: "Dam Alu" },
        { name: "Tameto Kon Bharta" },
        { name: "Baby Kon Butter Masala" },
        { name: "Chana Masala" },
        { name: "Kaju Kari Masala" },
        { name: "Kaju Butter Masala" },
        { name: "Kaju Masala" },
        { name: "Kaju Paneer" },
        { name: "Kaju Kashmiri (sweet)" },
        { name: "Koya Kaju (sweet)" },
      ],
    },
    {
      id: 6,
      name: "VegeTable Variety",
      items: [
        { name: "Veg. Darbari" },
        { name: "Veg. Jaypuri" },
        { name: "Veg. Singapuri" },
        { name: "Veg. Toofani" },
        { name: "Veg. Kolhapuri" },
        { name: "Veg. Kadai" },
        { name: "Veg. Tawa Masala" },
        { name: "Veg. Handi" },
        { name: "Veg. Hyderabadi" },
        { name: "Veg. Makhanwala" },
        { name: "Veg. Rajarani" },
        { name: "Veg. Kima Masala" },
        { name: "Veg. Hariyali" },
        { name: "Veg. Navaratan Korma" },
        { name: "Veg. Jafrani" },
        { name: "Veg. Mashroom Masala" },
        { name: "Veg. Korama" },
        { name: "Veg. Hangama" },
        { name: "Veg. Angara" },
        { name: "Veg. Tiranga" },
        { name: "Tomato Cone Bhartha" },
        { name: "Palak Cone Capsicum" },
        { name: "Mutter Capsicum" },
        { name: "Veg. Diwani" },
        { name: "Shahi Veg." },
        { name: "Capsicum Tomato" },
        { name: "Cone Bhartha" },
        { name: "Alu Cepsicum" },
        { name: "Mutter Palak" },
        { name: "Mix Vegetable" },
      ],
    },
    {
      id: 7,
      name: "Kathiyawadi",
      items: [
        { name: "Kadhi Khichdi" },
        { name: "Vagharelo Rotalo" },
        { name: "Masala Rotalo" },
        { name: "Lasaniya Bataka" },
        { name: "Kobitch Masala" },
        { name: "Dungali Masala" },
        { name: "Mix Bhaji" },
        { name: "Bengan Bharela" },
        { name: "Bengan Bhartha" },
        { name: "Bengan Masala" },
        { name: "Girnari khichdi" },
        { name: "Bhindi Masala" },
        { name: "Sev Dungari" },
        { name: "Alu Bengan Rasawala" },
        { name: "Dahi Bhindi" },
        { name: "Kadhi Pakoda" },
        { name: "Alu Palak" },
        { name: "Mag Masala" },
        { name: "Sev Masala" },
        { name: "Sev Tomato" },
        { name: "Bataka Rasavala" },
        { name: "Dhokadi" },
        { name: "Plain Palak" },
        { name: "Sukibhaji" },
        { name: "Alu Matter" },
        { name: "Tomato Dungari" },
        { name: "Masala Khichadi" },
        { name: "Dahi Tikhari" },
        { name: "Mag Fry" },
        { name: "Bhindi Fry" },
        { name: "Plain Khichdi" },
      ],
    },
    {
      id: 8,
      name: "Raita",
      items: [
        { name: "Pineaple Raita" },
        { name: "Dahi Raita" },
        { name: "Veg. Raita" },
        { name: "Dungari Raita" },
        { name: "Bundi Raita" },
        { name: "Mix Fruit Raita" },
      ],
    },
    {
      id: 9,
      name: "Lassi",
      items: [
        { name: "Cold Coffee With Ice Cream" },
        { name: "Sweet Lassi" },
        { name: "Cold Coffee" },
      ],
    },
  ];
};
